name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: echo "Hello, this line is printed during the workflow!"
